# Generated by Django 4.2 on 2023-06-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='spare_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant_app.spareparts', verbose_name='Используемые запчасти'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
